version: '3.4'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: miapiresttest_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
